- - key: dep
    value: punct
  - key: tag
    value: ","
- - key: dep
    value: cc
- - key: tag
    value: NN
  - key: dep
    value: compound
- - key: dep
    value: aux
- - key: dep
    value: amod
- - key: tag
    value: IN
  - key: dep
    value: prep
- - how: starts
    key: tag
    value: NN
  - key: dep
    value: pobj
- - key: dep
    value: det
- - key: dep
    value: poss
- - how: starts
    key: tag
    value: NN
  - key: dep
    value: conj
- - key: tag
    value: CD
