linkers:
-   keyword: BERN_V2
    route: plain
    port: 8888
    text_field: text
    threshold: 0.75
-   keyword: PELINKER
    route: pelinker
    port: 8599
    text_field: text
-   keyword: FISHING
    route: service/disambiguate
    port: 8090
    protocol: http
    text_field: text
    extra_args:
        language:
            lang: en
        mentions: [ner, wikipedia]
