BERN_V2:
    url: http://bern2.korea.ac.kr/plain
    text_field: text
FISHING:
    url: http://localhost:8090/service/disambiguate
    text_field: text
    extra_args:
        language:
            lang: en
        mentions: [ner, wikipedia]
