source_target:
    primary:
    -   -   how: startswith
            key: tag_
            value: NN
        -   how: __ne__
            key: dep_
            value: compound
    -   -   key: tag_
            value: PRP
    -   -   key: tag_
            value: DT
        -   key: dep_
            value: nsubj
    -   -   key: tag_
            value: CD
        -   key: dep_
            value: nsubj
    -   -   key: tag_
            value: VBG
        -   key: dep_
            value: nsubj
#    - - how: startswith
#        key: tag_
#        value: JJ
#      - key: dep_
#        value: acomp
    secondary:
    -   -   key: dep_
            value: punct
    -   -   key: dep_
            value: cc
    -   -   key: dep_
            value: aux
    -   -   key: dep_
            value: amod
    -   -   key: dep_
            value: det
    -   -   key: dep_
            value: poss
    -   -   how: startswith
            key: tag_
            value: NN
        -   key: dep_
            value: conj
    -   -   how: startswith
            key: tag_
            value: NN
        -   key: dep_
            value: dobj
    -   -   how: startswith
            key: tag_
            value: NN
        -   key: dep_
            value: npadvmod
    -   -   how: startswith
            key: tag_
            value: NN
        -   key: dep_
            value: compound
    -   -   key: tag_
            value: CD
    -   -   key: tag_
            value: IN
        -   key: dep_
            value: prep
    -   -   how: startswith
            key: tag_
            value: NN
        -   key: dep_
            value: pobj
    -   -   key: tag_
            value: CD
        -   key: dep_
            value: nummod
    -   -   key: tag_
            value: NN
        -   key: dep_
            value: nummod
    -   -   key: tag_
            value: IN
        -   key: dep_
            value: nmod
    -   -   how: startswith
            key: tag_
            value: VB
        -   key: dep_
            value: conj
relation:
    primary:
    -   -   how: startswith
            key: tag_
            value: VB
        -   how: __ne__
            key: dep_
            value: amod
        -   how: __ne__
            key: dep_
            value: nsubj
        -   how: __ne__
            key: dep_
            value: conj
        -   how: __ne__
            key: dep_
            value: xcomp
    -   -   key: tag_
            value: VBN
        -   key: dep_
            value: acl
    secondary:
    -   -   how: startswith
            key: tag_
            value: VB
        -   how: __contains__
            key: dep_
            value: aux
    -   -   key: tag_
            value: MD
        -   how: __contains__
            key: dep_
            value: aux
    -   -   key: tag_
            value: VBG
        -   key: dep_
            value: advcl
    -   -   how: startswith
            key: tag_
            value: JJ
        -   key: dep_
            value: acomp
    -   -   how: startswith
            key: tag_
            value: VBG
        -   key: dep_
            value: pcomp
    -   -   how: startswith
            key: tag_
            value: VBN
        -   key: dep_
            value: acomp
    -   -   how: startswith
            key: tag_
            value: VB
        -   key: dep_
            value: xcomp
    -   -   key: tag_
            value: TO
        -   key: dep_
            value: aux
    secondary_preceding:
    -   -   key: tag_
            value: IN
        -   key: dep_
            value: prep
    -   -   key: tag_
            value: IN
        -   key: dep_
            value: agent
